# 말로하는 지도 만들기라는 거창한 프로젝트를 위해... DB와의 통신이 필요해졌기에
- 로컬모델으로 서빙하는 agent
- 자연어 쿼리를 통한 mappick에서 서비스하고 있는 레이어 불러오기

# Quickstart
- 이 가이드에서는 SQL 데이터베이스를 사용하여 Q&A 체인과 에이전트를 만드는 기본적인 방법을 살펴볼 것입니다. 
- 이 시스템들을 통해 SQL 데이터베이스에 대한 질문을 하고 자연어 답변을 받을 수 있습니다. 
- 두 시스템의 주요 차이점은 에이전트가 질문에 답하기 위해 필요한 만큼 데이터베이스를 반복적으로 쿼리할 수 있다는 것입니다.

# ⚠️ Security note ⚠️
- SQL 데이터베이스의 Q&A 시스템을 구축하는 것은 모델이 생성한 SQL 쿼리를 실행해야 합니다. 
- 이 과정에는 본질적인 위험이 따릅니다. 
- 데이터베이스 연결 권한을 항상 체인/에이전트의 필요에 맞게 가능한 한 좁게 설정해야 합니다. 
- 이는 위험을 완전히 제거하지는 않지만 줄일 수 있습니다. 일반적인 보안 모범 사례에 대해서는 여기를 참조하세요.

# Architecture
- 전반적으로, 모든 SQL 체인과 에이전트의 단계는 다음과 같습니다:
- 질문을 SQL 쿼리로 변환: 모델이 사용자 입력을 SQL 쿼리로 변환합니다.
- SQL 쿼리 실행: SQL 쿼리를 실행합니다.
- 질문에 답하기: 모델이 쿼리 결과를 사용하여 사용자 입력에 응답합니다.

In [37]:
from dotenv import load_dotenv
load_dotenv('/Users/kownkihoon/Desktop/업무_wavus/0.GeOnAI/dot.env')
import os
import getpass
from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.agents import AgentExecutor

from langchain.sql_database import SQLDatabase
from connection_info import db

def _set_if_undefined(var: str):
    # 주어진 환경 변수가 설정되어 있지 않다면 사용자에게 입력을 요청하여 설정합니다.
    if not os.environ.get(var):
        os.environ[var] = getpass.getpass(f"Please provide your {var}")


# OPENAI_API_KEY 환경 변수가 설정되어 있지 않으면 사용자에게 입력을 요청합니다.
_set_if_undefined("OPENAI_API_KEY")
# LANGCHAIN_API_KEY 환경 변수가 설정되어 있지 않으면 사용자에게 입력을 요청합니다.
_set_if_undefined("LANGCHAIN_API_KEY")
# TAVILY_API_KEY 환경 변수가 설정되어 있지 않으면 사용자에게 입력을 요청합니다.
_set_if_undefined("TAVILY_API_KEY")

# LangSmith 추적 기능을 활성화합니다. (선택적)
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_PROJECT"] = "GeOnAI_DBchain"

# connection 생성
db = db

# 로컬에 설치한 DB와의 연결

In [38]:
from langchain_community.utilities import SQLDatabase

# print(db.get_usable_table_names())

#

# sql문 리턴 성능
- gpt-3.5-turbo: 완벽
- xionic-ko-llama-3-70b: 미달
- QuantFactory/dolphin-2.9-llama3-8b-GGUF: 상(프롬프트 조작을 통해 사용 가능)
- mradermacher_f16/Joah-Remix-Llama-3-KoEn-8B-Reborn-GGUF: 상(프롬프트 조작을 통해 사용 가능)
- asiansoul_q8_0/Joah-Remix-Llama-3-KoEn-8B-Reborn-8B-Q8_0: 상(프롬프트 조작을 통해 사용 가능)

In [39]:
from langchain.chains import create_sql_query_chain
from langchain_openai import ChatOpenAI
from langchain_core.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain_core.prompts import PromptTemplate
from langchain import hub
from langchain_core.output_parsers import StrOutputParser


# llm = ChatOpenAI(model="gpt-3.5-turbo",
#                 temperature=0,
#                 streaming=True,
#     callbacks=[StreamingStdOutCallbackHandler()]
#                 )

llm = ChatOpenAI(
    base_url="http://localhost:1234/v1", #-> lmstudio를 통해 열어놓은 서버로 llm을 구동하고 있는 상태, lmstudio에 서빙하고 있는 모델만 바꿔주면 새로 나온 모델을 시험해볼 수 있음
    api_key="lm-studio",
    model="asiansoul_q8_0/Joah-Remix-Llama-3-KoEn-8B-Reborn-8B-Q8_0",
    temperature=0,
    streaming=True,
    callbacks=[StreamingStdOutCallbackHandler()]
)

# ----------------------------------------------
prompt = hub.pull("rlm/text-to-sql")

# Create chain with LangChain Expression Language
inputs = {
    # "table_info": lambda x: db.get_table_info(), #->여기에 맵핑정보 넣어주면???
    "table_info": lambda x: db.get_table_names(), #->table_info 사용 시 정보량이 많아 오류
    "input": lambda x: x["question"],
    "few_shot_examples": lambda x: "",
    "dialect": lambda x: db.dialect,
}
# ----------------------------------------------

sql_response = (
    inputs
    | prompt
    | llm.bind(stop=["SQLResult:"])
    | StrOutputParser()
    | (lambda x: x.split("SQLQuery: ")[1]) #LCED의 lambda 사용법 익히기
)

# Call with a given question
response = sql_response.invoke({"question": "테이블명에 선거가 포함되는 테이블은?"})
db.run(response)

SQLQuery: SELECT table_name FROM information_schema.tables WHERE table_name LIKE '%선거%';

"[('선거지도_21대총선_동',)]"

In [34]:
db.get_context()['table_info']

'\nCREATE TABLE gfdata."선거지도_21대총선_동" (\n\tfid INTEGER DEFAULT nextval(\'gfdata.l100005158_fid_seq\'::regclass) NOT NULL, \n\t"ADM_DR_CD" VARCHAR, \n\t"ADM_DR_NM" VARCHAR, \n\t"SIGUNGU_CD" VARCHAR, \n\t"SIDO_CD" VARCHAR, \n\t"DISTRICT" VARCHAR, \n\t"POP_VT" BIGINT, \n\t"SCS_CD" VARCHAR, \n\t"SCS_PRT" VARCHAR, \n\t"SIGUNGU_NM" VARCHAR, \n\t"SIDO_NM" VARCHAR, \n\t"ALIAS" VARCHAR\n)\n\n/*\n3 rows from 선거지도_21대총선_동 table:\nfid\tADM_DR_CD\tADM_DR_NM\tSIGUNGU_CD\tSIDO_CD\tDISTRICT\tPOP_VT\tSCS_CD\tSCS_PRT\tSIGUNGU_NM\tSIDO_NM\tALIAS\n1\t1101053\t사직동\t11010\t11\t종로구\t7751\t황교안\t미래통합당\t종로구\t서울특별시\t종로\n2\t1101054\t삼청동\t11010\t11\t종로구\t2237\t이낙연\t더불어민주당\t종로구\t서울특별시\t종로\n3\t1101055\t부암동\t11010\t11\t종로구\t7850\t이낙연\t더불어민주당\t종로구\t서울특별시\t종로\n*/\n\n\nCREATE TABLE gfdata.age_group_popltn (\n\tgid SERIAL NOT NULL, \n\t__gid VARCHAR(254), \n\ta_pre_a BIGINT, \n\ta_pre_m BIGINT, \n\ta_pre_f BIGINT, \n\ta_ele_a BIGINT, \n\ta_ele_m BIGINT, \n\ta_ele_f BIGINT, \n\ta_mid_a BIGINT, \n\ta_mid_m BIGINT, \n\ta_mid_f BIGINT, \n\ta_hig_a BIGINT, \n\ta_hig_m BIGINT, \n\ta_hig_f BIGINT, \n\ta_020_a BIGINT, \n\ta_020_m BIGINT, \n\ta_020_f BIGINT, \n\ta_030_a BIGINT, \n\ta_030_m BIGINT, \n\ta_030_f BIGINT, \n\ta_040_a BIGINT, \n\ta_040_m BIGINT, \n\ta_040_f BIGINT, \n\ta_050_a BIGINT, \n\ta_050_m BIGINT, \n\ta_050_f BIGINT, \n\ta_060_a BIGINT, \n\ta_060_m BIGINT, \n\ta_060_f BIGINT, \n\ta_070_a BIGINT, \n\ta_070_m BIGINT, \n\ta_070_f BIGINT, \n\ta_080_a BIGINT, \n\ta_080_m BIGINT, \n\ta_080_f BIGINT, \n\ta_090_a BIGINT, \n\ta_090_m BIGINT, \n\ta_090_f BIGINT, \n\ta_100_a BIGINT, \n\ta_100_m BIGINT, \n\ta_100_f BIGINT, \n\tsido_cd VARCHAR(10), \n\tsgg_cd VARCHAR(10), \n\tCONSTRAINT age_group_population_new_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from age_group_popltn table:\ngid\t__gid\ta_pre_a\ta_pre_m\ta_pre_f\ta_ele_a\ta_ele_m\ta_ele_f\ta_mid_a\ta_mid_m\ta_mid_f\ta_hig_a\ta_hig_m\ta_hig_f\ta_020_a\ta_020_m\ta_020_f\ta_030_a\ta_030_m\ta_030_f\ta_040_a\ta_040_m\ta_040_f\ta_050_a\ta_050_m\ta_050_f\ta_060_a\ta_060_m\ta_060_f\ta_070_a\ta_070_m\ta_070_f\ta_080_a\ta_080_m\ta_080_f\ta_090_a\ta_090_m\ta_090_f\ta_100_a\ta_100_m\ta_100_f\tsido_cd\tsgg_cd\n1\t다사613448\t6\t0\t0\t10\t9\t0\t8\t0\t0\t9\t6\t0\t26\t15\t11\t25\t14\t11\t19\t8\t11\t43\t23\t20\t37\t14\t23\t18\t11\t7\t10\t0\t8\t0\t0\t0\t0\t0\t0\t11\t230\n2\t다사583456\t6\t0\t0\t9\t6\t0\t0\t0\t0\t0\t0\t0\t76\t44\t32\t145\t72\t73\t92\t44\t48\t42\t20\t22\t33\t14\t19\t20\t10\t10\t7\t0\t0\t0\t0\t0\t0\t0\t0\t11\t230\n3\t다사597458\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t16\t9\t7\t10\t8\t0\t0\t0\t0\t17\t9\t8\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t11\t230\n*/\n\n\nCREATE TABLE gfdata.al_11_d010_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_11_d010_new_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_11_d010_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n13696384\t32\t1991201839054527769900000000\t1111017500107040000\t1111017500\t서울특별시 종로구 숭인동\t704\t1\t일반\t01000\t단독주택\t39\t기타강구조\t57.6\t1991-09-02\t203.13\t100.6\t9.1\t57.26\t144.66202\t29692\tN\tB00100000000T30Z9\t2024-05-01\t11110\tNone\tNone\t3\t0\t2017-05-30\n13696385\t34\t1967201343844527773800000000\t1111017500100560024\t1111017500\t서울특별시 종로구 숭인동\t56-24\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1967-05-28\t114.98\t0.0\t0.0\t0.0\t0.0\t12540\tN\tB00100000000T311B\t2024-05-01\t11110\tNone\tNone\t3\t0\t2018-06-19\n13696386\t36\t1962201375194527742000000000\t1111017500100560054\t1111017500\t서울특별시 종로구 숭인동\t56-54\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1962-12-21\t135.2\t0.0\t0.0\t0.0\t0.0\t24867\tN\tB00100000000T313D\t2024-05-01\t11110\tNone\tNone\t2\t0\t2017-02-24\n*/\n\n\nCREATE TABLE gfdata.al_11_d010_new_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_11_d010_new_new_40_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_11_d010_new_202403 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n13696326\t32\t1991201839054527769900000000\t1111017500107040000\t1111017500\t서울특별시 종로구 숭인동\t704\t1\t일반\t01000\t단독주택\t39\t기타강구조\t57.6\t1991-09-02\t203.13\t100.6\t9.1\t57.26\t144.66202\t29692\tN\tB00100000000T30Z9\t2024-04-01\t11110\tNone\tNone\t3\t0\t2017-05-30\n13696327\t34\t1967201343844527773800000000\t1111017500100560024\t1111017500\t서울특별시 종로구 숭인동\t56-24\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1967-05-28\t114.98\t0.0\t0.0\t0.0\t0.0\t12540\tN\tB00100000000T311B\t2024-04-01\t11110\tNone\tNone\t3\t0\t2018-06-19\n13696328\t36\t1962201375194527742000000000\t1111017500100560054\t1111017500\t서울특별시 종로구 숭인동\t56-54\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1962-12-21\t135.2\t0.0\t0.0\t0.0\t0.0\t24867\tN\tB00100000000T313D\t2024-04-01\t11110\tNone\tNone\t2\t0\t2017-02-24\n*/\n\n\nCREATE TABLE gfdata.al_11_d010_new_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_11_d010_new_new_45_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_11_d010_new_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n13696373\t32\t1991201839054527769900000000\t1111017500107040000\t1111017500\t서울특별시 종로구 숭인동\t704\t1\t일반\t01000\t단독주택\t39\t기타강구조\t57.6\t1991-09-02\t203.13\t100.6\t9.1\t57.26\t144.66202\t29692\tN\tB00100000000T30Z9\t2024-06-04\t11110\tNone\tNone\t3\t0\t2017-05-30\n13696374\t34\t1967201343844527773800000000\t1111017500100560024\t1111017500\t서울특별시 종로구 숭인동\t56-24\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1967-05-28\t114.98\t0.0\t0.0\t0.0\t0.0\t12540\tN\tB00100000000T311B\t2024-06-04\t11110\tNone\tNone\t3\t0\t2018-06-19\n13696375\t36\t1962201375194527742000000000\t1111017500100560054\t1111017500\t서울특별시 종로구 숭인동\t56-54\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1962-12-21\t135.2\t0.0\t0.0\t0.0\t0.0\t24867\tN\tB00100000000T313D\t2024-06-04\t11110\tNone\tNone\t2\t0\t2017-02-24\n*/\n\n\nCREATE TABLE gfdata.al_26_d010 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_26_d010_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_26_d010 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n11513932\t223\t1998202070161786836800000000\t2611012000100160026\t2611012000\t부산광역시 중구 보수동1가\t16-26\t1\t일반\t02000\t공동주택\t21\t철근콘크리트구조\t57.74\t1998-05-01\t230.96\t69.2\t11.95\t83.44\t333.76\t7759\tN\tB0010000000B0N8EX\t2024-05-01\t26110\tNone\tNone\t4\t0\t2011-01-13\n11513933\t484\t1978201965801784846100000000\t2611012200100090004\t2611012200\t부산광역시 중구 보수동3가\t9-4\t1\t일반\t01000\t단독주택\t12\t블록구조\t52.2\t1978-01-23\t78.38\t0.0\t0.0\t0.0\t0.0\t8549\tN\tB0010000000B0QGNI\t2024-05-01\t26110\tNone\tNone\t2\t0\t2017-11-02\n11513934\t225\t1992202154291786601000000000\t2611012000100330016\t2611012000\t부산광역시 중구 보수동1가\t33-16\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t60.13\t1992-10-12\t199.74\t113.56\t6.96\t52.95\t103.62\t6618\tN\tB0010000000B0U6XM\t2024-05-01\t26110\tNone\tNone\t2\t1\t2011-01-13\n*/\n\n\nCREATE TABLE gfdata.al_26_d010_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_26_d010_new_40_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_26_d010_202403 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n11514134\t223\t1998202070161786836800000000\t2611012000100160026\t2611012000\t부산광역시 중구 보수동1가\t16-26\t1\t일반\t02000\t공동주택\t21\t철근콘크리트구조\t57.74\t1998-05-01\t230.96\t69.2\t11.95\t83.44\t333.76\t7759\tN\tB0010000000B0N8EX\t2024-04-01\t26110\tNone\tNone\t4\t0\t2011-01-13\n11514135\t484\t1978201965801784846100000000\t2611012200100090004\t2611012200\t부산광역시 중구 보수동3가\t9-4\t1\t일반\t01000\t단독주택\t12\t블록구조\t52.2\t1978-01-23\t78.38\t0.0\t0.0\t0.0\t0.0\t8549\tN\tB0010000000B0QGNI\t2024-04-01\t26110\tNone\tNone\t2\t0\t2017-11-02\n11514136\t225\t1992202154291786601000000000\t2611012000100330016\t2611012000\t부산광역시 중구 보수동1가\t33-16\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t60.13\t1992-10-12\t199.74\t113.56\t6.96\t52.95\t103.62\t6618\tN\tB0010000000B0U6XM\t2024-04-01\t26110\tNone\tNone\t2\t1\t2011-01-13\n*/\n\n\nCREATE TABLE gfdata.al_26_d010_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_26_d010_new_45_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_26_d010_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n11513671\t223\t1998202070161786836800000000\t2611012000100160026\t2611012000\t부산광역시 중구 보수동1가\t16-26\t1\t일반\t02000\t공동주택\t21\t철근콘크리트구조\t57.74\t1998-05-01\t230.96\t69.2\t11.95\t83.44\t333.76\t7759\tN\tB0010000000B0N8EX\t2024-06-04\t26110\tNone\tNone\t4\t0\t2011-01-13\n11513672\t484\t1978201965801784846100000000\t2611012200100090004\t2611012200\t부산광역시 중구 보수동3가\t9-4\t1\t일반\t01000\t단독주택\t12\t블록구조\t52.2\t1978-01-23\t78.38\t0.0\t0.0\t0.0\t0.0\t8549\tN\tB0010000000B0QGNI\t2024-06-04\t26110\tNone\tNone\t2\t0\t2017-11-02\n11513673\t225\t1992202154291786601000000000\t2611012000100330016\t2611012000\t부산광역시 중구 보수동1가\t33-16\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t60.13\t1992-10-12\t199.74\t113.56\t6.96\t52.95\t103.62\t6618\tN\tB0010000000B0U6XM\t2024-06-04\t26110\tNone\tNone\t2\t1\t2011-01-13\n*/\n\n\nCREATE TABLE gfdata.al_27_d010 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_27_d010_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_27_d010 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10756935\t46627\t1949163376372622421000000000\t2711015600107350049\t2711015600\t대구광역시 중구 남산동\t735-49\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1949-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-05-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756936\t36767\t0000163261862627417000000000\t2711015600109210027\t2711015600\t대구광역시 중구 남산동\t921-27\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-05-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756937\t35691\t1967162308722621416300000000\t2711015600124210007\t2711015600\t대구광역시 중구 남산동\t2421-7\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1967-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-05-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n*/\n\n\nCREATE TABLE gfdata.al_27_d010_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_27_d010_new_40_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_27_d010_202403 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10756974\t46627\t1949163376372622421000000000\t2711015600107350049\t2711015600\t대구광역시 중구 남산동\t735-49\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1949-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-04-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756975\t36767\t0000163261862627417000000000\t2711015600109210027\t2711015600\t대구광역시 중구 남산동\t921-27\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-04-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756976\t35691\t1967162308722621416300000000\t2711015600124210007\t2711015600\t대구광역시 중구 남산동\t2421-7\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1967-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-04-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n*/\n\n\nCREATE TABLE gfdata.al_27_d010_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_27_d010_new_45_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_27_d010_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10756939\t46627\t1949163376372622421000000000\t2711015600107350049\t2711015600\t대구광역시 중구 남산동\t735-49\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1949-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-06-04\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756940\t36767\t0000163261862627417000000000\t2711015600109210027\t2711015600\t대구광역시 중구 남산동\t921-27\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-06-04\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756941\t35691\t1967162308722621416300000000\t2711015600124210007\t2711015600\t대구광역시 중구 남산동\t2421-7\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1967-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-06-04\t27110\tNone\tNone\t0\t0\t2010-01-19\n*/\n\n\nCREATE TABLE gfdata.al_28_d010 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_28_d010_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_28_d010 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10460910\t69\t0000147661854315781200000000\t2811015200201890000\t2811015200\t인천광역시 중구 무의동\t189\t2\t산\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tB00100000001AV3E1\t2024-05-01\t28110\tNone\tNone\t0\t0\t2011-11-16\n10460911\t70\t0000147663704315722500000000\t2811015200201890000\t2811015200\t인천광역시 중구 무의동\t189\t2\t산\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tB00100000001AV3F2\t2024-05-01\t28110\tNone\tNone\t0\t0\t2011-11-16\n10460912\t72\t0000147958424314062300000000\t2811015200100800001\t2811015200\t인천광역시 중구 무의동\t80-1\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tB00100000001AV7D4\t2024-05-01\t28110\tNone\tNone\t0\t0\t2011-11-16\n*/\n\n\nCREATE TABLE gfdata.al_28_d010_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\

In [28]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings


data = db.get_context()['table_info']

# text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, 
#                                                chunk_overlap=0,
#                                                split_text='CREATE TABLE')

from langchain_text_splitters import CharacterTextSplitter

text_splitter = CharacterTextSplitter(
    # 텍스트를 분할할 때 사용할 구분자를 지정합니다. 기본값은 "\n\n"입니다.
    separator="CREATE TABLE",
    # 분할된 텍스트 청크의 최대 크기를 지정합니다.
    chunk_size=250,
    # 분할된 텍스트 청크 간의 중복되는 문자 수를 지정합니다.
    chunk_overlap=50,
    # 텍스트의 길이를 계산하는 함수를 지정합니다.
    length_function=len,
    # 구분자가 정규식인지 여부를 지정합니다.
    is_separator_regex=False,
)

all_splits = text_splitter.create_documents([data])

vectorstore = Chroma.from_documents(documents=all_splits, embedding=OpenAIEmbeddings())

# k is the number of chunks to retrieve
retriever = vectorstore.as_retriever(k=4)

docs = retriever.invoke("21대총선")

docs

Created a chunk of size 648, which is longer than the specified 250
Created a chunk of size 1591, which is longer than the specified 250
Created a chunk of size 1488, which is longer than the specified 250
Created a chunk of size 1502, which is longer than the specified 250
Created a chunk of size 1496, which is longer than the specified 250
Created a chunk of size 1493, which is longer than the specified 250
Created a chunk of size 1507, which is longer than the specified 250
Created a chunk of size 1501, which is longer than the specified 250
Created a chunk of size 1431, which is longer than the specified 250
Created a chunk of size 1445, which is longer than the specified 250
Created a chunk of size 1439, which is longer than the specified 250
Created a chunk of size 1439, which is longer than the specified 250
Created a chunk of size 1453, which is longer than the specified 250
Created a chunk of size 1447, which is longer than the specified 250
Created a chunk of size 1411, which is longer than the specified 250
Created a chunk of size 1425, which is longer than the specified 250
Created a chunk of size 1419, which is longer than the specified 250
Created a chunk of size 1399, which is longer than the specified 250
Created a chunk of size 1413, which is longer than the specified 250
Created a chunk of size 1407, which is longer than the specified 250
Created a chunk of size 1410, which is longer than the specified 250
Created a chunk of size 1424, which is longer than the specified 250
Created a chunk of size 1418, which is longer than the specified 250
Created a chunk of size 1420, which is longer than the specified 250
Created a chunk of size 1434, which is longer than the specified 250
Created a chunk of size 1428, which is longer than the specified 250
Created a chunk of size 1514, which is longer than the specified 250
Created a chunk of size 1449, which is longer than the specified 250
Created a chunk of size 1529, which is longer than the specified 250
Created a chunk of size 1422, which is longer than the specified 250
Created a chunk of size 1436, which is longer than the specified 250
Created a chunk of size 1430, which is longer than the specified 250
Created a chunk of size 1420, which is longer than the specified 250
Created a chunk of size 1434, which is longer than the specified 250
Created a chunk of size 1428, which is longer than the specified 250
Created a chunk of size 1427, which is longer than the specified 250
Created a chunk of size 1475, which is longer than the specified 250
Created a chunk of size 1450, which is longer than the specified 250
Created a chunk of size 1477, which is longer than the specified 250
Created a chunk of size 1491, which is longer than the specified 250
Created a chunk of size 1485, which is longer than the specified 250
Created a chunk of size 1449, which is longer than the specified 250
Created a chunk of size 1439, which is longer than the specified 250
Created a chunk of size 1433, which is longer than the specified 250
Created a chunk of size 1443, which is longer than the specified 250
Created a chunk of size 1498, which is longer than the specified 250
Created a chunk of size 1464, which is longer than the specified 250
Created a chunk of size 1401, which is longer than the specified 250
Created a chunk of size 1457, which is longer than the specified 250
Created a chunk of size 1451, which is longer than the specified 250
Created a chunk of size 1416, which is longer than the specified 250
Created a chunk of size 1430, which is longer than the specified 250
Created a chunk of size 1424, which is longer than the specified 250
Created a chunk of size 1413, which is longer than the specified 250
Created a chunk of size 1425, which is longer than the specified 250
Created a chunk of size 1421, which is longer than the specified 250
Created a chunk of size 293, which is longer than the specified 250
Created a chunk of size 1627, which is longer than the specified 250
Created a chunk of size 4391, which is longer than the specified 250
Created a chunk of size 4423, which is longer than the specified 250
Created a chunk of size 1439, which is longer than the specified 250
Created a chunk of size 3620, which is longer than the specified 250
Created a chunk of size 3985, which is longer than the specified 250
Created a chunk of size 392, which is longer than the specified 250
Created a chunk of size 297, which is longer than the specified 250
Created a chunk of size 251, which is longer than the specified 250
Created a chunk of size 336, which is longer than the specified 250
Created a chunk of size 342, which is longer than the specified 250
Created a chunk of size 356, which is longer than the specified 250
Created a chunk of size 338, which is longer than the specified 250
Created a chunk of size 352, which is longer than the specified 250
Created a chunk of size 340, which is longer than the specified 250
Created a chunk of size 354, which is longer than the specified 250
Created a chunk of size 335, which is longer than the specified 250
Created a chunk of size 349, which is longer than the specified 250
Created a chunk of size 338, which is longer than the specified 250
Created a chunk of size 352, which is longer than the specified 250
Created a chunk of size 342, which is longer than the specified 250
Created a chunk of size 356, which is longer than the specified 250
Created a chunk of size 341, which is longer than the specified 250
Created a chunk of size 355, which is longer than the specified 250
Created a chunk of size 343, which is longer than the specified 250
Created a chunk of size 357, which is longer than the specified 250
Created a chunk of size 343, which is longer than the specified 250
Created a chunk of size 357, which is longer than the specified 250
Created a chunk of size 341, which is longer than the specified 250
Created a chunk of size 355, which is longer than the specified 250
Created a chunk of size 343, which is longer than the specified 250
Created a chunk of size 357, which is longer than the specified 250
Created a chunk of size 337, which is longer than the specified 250
Created a chunk of size 351, which is longer than the specified 250
Created a chunk of size 345, which is longer than the specified 250
Created a chunk of size 359, which is longer than the specified 250
Created a chunk of size 339, which is longer than the specified 250
Created a chunk of size 353, which is longer than the specified 250
Created a chunk of size 348, which is longer than the specified 250
Created a chunk of size 362, which is longer than the specified 250
Created a chunk of size 344, which is longer than the specified 250
Created a chunk of size 358, which is longer than the specified 250
Created a chunk of size 338, which is longer than the specified 250
Created a chunk of size 352, which is longer than the specified 250
Created a chunk of size 344, which is longer than the specified 250
Created a chunk of size 358, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 533, which is longer than the specified 250
Created a chunk of size 539, which is longer than the specified 250
Created a chunk of size 368, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 1063, which is longer than the specified 250
Created a chunk of size 522, which is longer than the specified 250
Created a chunk of size 269, which is longer than the specified 250
Created a chunk of size 279, which is longer than the specified 250
Created a chunk of size 310, which is longer than the specified 250
Created a chunk of size 1068, which is longer than the specified 250
Created a chunk of size 923, which is longer than the specified 250
Created a chunk of size 275, which is longer than the specified 250
Created a chunk of size 251, which is longer than the specified 250
Created a chunk of size 571, which is longer than the specified 250
Created a chunk of size 1629, which is longer than the specified 250
Created a chunk of size 712, which is longer than the specified 250
Created a chunk of size 559, which is longer than the specified 250
Created a chunk of size 308, which is longer than the specified 250
Created a chunk of size 885, which is longer than the specified 250
Created a chunk of size 1928, which is longer than the specified 250
Created a chunk of size 2157, which is longer than the specified 250
Created a chunk of size 2351, which is longer than the specified 250
Created a chunk of size 2124, which is longer than the specified 250
Created a chunk of size 1929, which is longer than the specified 250
Created a chunk of size 1825, which is longer than the specified 250
Created a chunk of size 1950, which is longer than the specified 250
Created a chunk of size 2089, which is longer than the specified 250
Created a chunk of size 962, which is longer than the specified 250
Created a chunk of size 1695, which is longer than the specified 250
Created a chunk of size 2076, which is longer than the specified 250
Created a chunk of size 836, which is longer than the specified 250
Created a chunk of size 2315, which is longer than the specified 250
Created a chunk of size 932, which is longer than the specified 250
Created a chunk of size 259, which is longer than the specified 250
Created a chunk of size 1996, which is longer than the specified 250
Created a chunk of size 1961, which is longer than the specified 250
Created a chunk of size 2144, which is longer than the specified 250
Created a chunk of size 1648, which is longer than the specified 250
Created a chunk of size 711, which is longer than the specified 250
Created a chunk of size 1713, which is longer than the specified 250
Created a chunk of size 760, which is longer than the specified 250
Created a chunk of size 327, which is longer than the specified 250
Created a chunk of size 339, which is longer than the specified 250
Created a chunk of size 339, which is longer than the specified 250
Created a chunk of size 341, which is longer than the specified 250
Created a chunk of size 339, which is longer than the specified 250
Created a chunk of size 339, which is longer than the specified 250
Created a chunk of size 335, which is longer than the specified 250
Created a chunk of size 330, which is longer than the specified 250
Created a chunk of size 369, which is longer than the specified 250
Created a chunk of size 348, which is longer than the specified 250
Created a chunk of size 346, which is longer than the specified 250
Created a chunk of size 342, which is longer than the specified 250
Created a chunk of size 342, which is longer than the specified 250
Created a chunk of size 338, which is longer than the specified 250
Created a chunk of size 324, which is longer than the specified 250
Created a chunk of size 337, which is longer than the specified 250
Created a chunk of size 344, which is longer than the specified 250
Created a chunk of size 341, which is longer than the specified 250
Created a chunk of size 336, which is longer than the specified 250
Created a chunk of size 336, which is longer than the specified 250
Created a chunk of size 332, which is longer than the specified 250
Created a chunk of size 319, which is longer than the specified 250
Created a chunk of size 351, which is longer than the specified 250
Created a chunk of size 332, which is longer than the specified 250
Created a chunk of size 322, which is longer than the specified 250
Created a chunk of size 331, which is longer than the specified 250
Created a chunk of size 331, which is longer than the specified 250
Created a chunk of size 327, which is longer than the specified 250
Created a chunk of size 671, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 697, which is longer than the specified 250
Created a chunk of size 681, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 453, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 453, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 452, which is longer than the specified 250
Created a chunk of size 679, which is longer than the specified 250
Created a chunk of size 495, which is longer than the specified 250
Created a chunk of size 503, which is longer than the specified 250
Created a chunk of size 503, which is longer than the specified 250
Created a chunk of size 505, which is longer than the specified 250
Created a chunk of size 503, which is longer than the specified 250
Created a chunk of size 612, which is longer than the specified 250
Created a chunk of size 631, which is longer than the specified 250
Created a chunk of size 621, which is longer than the specified 250
Created a chunk of size 623, which is longer than the specified 250
Created a chunk of size 589, which is longer than the specified 250
Created a chunk of size 601, which is longer than the specified 250
Created a chunk of size 611, which is longer than the specified 250
Created a chunk of size 597, which is longer than the specified 250
Created a chunk of size 1353, which is longer than the specified 250
Created a chunk of size 1365, which is longer than the specified 250
Created a chunk of size 1361, which is longer than the specified 250
Created a chunk of size 309, which is longer than the specified 250
Created a chunk of size 321, which is longer than the specified 250
Created a chunk of size 318, which is longer than the specified 250
Created a chunk of size 317, which is longer than the specified 250
Created a chunk of size 392, which is longer than the specified 250
Created a chunk of size 369, which is longer than the specified 250
Created a chunk of size 402, which is longer than the specified 250
Created a chunk of size 404, which is longer than the specified 250
Created a chunk of size 400, which is longer than the specified 250
Created a chunk of size 361, which is longer than the specified 250
Created a chunk of size 372, which is longer than the specified 250
Created a chunk of size 372, which is longer than the specified 250
Created a chunk of size 373, which is longer than the specified 250
Created a chunk of size 369, which is longer than the specified 250
Created a chunk of size 377, which is longer than the specified 250
Created a chunk of size 387, which is longer than the specified 250
Created a chunk of size 389, which is longer than the specified 250
Created a chunk of size 385, which is longer than the specified 250
Created a chunk of size 396, which is longer than the specified 250
Created a chunk of size 406, which is longer than the specified 250
Created a chunk of size 408, which is longer than the specified 250
Created a chunk of size 404, which is longer than the specified 250
Created a chunk of size 365, which is longer than the specified 250
Created a chunk of size 376, which is longer than the specified 250
Created a chunk of size 375, which is longer than the specified 250
Created a chunk of size 377, which is longer than the specified 250
Created a chunk of size 373, which is longer than the specified 250
Created a chunk of size 1139, which is longer than the specified 250
Created a chunk of size 1677, which is longer than the specified 250
Created a chunk of size 1188, which is longer than the specified 250
Created a chunk of size 407, which is longer than the specified 250
Created a chunk of size 345, which is longer than the specified 250
Created a chunk of size 387, which is longer than the specified 250
Created a chunk of size 325, which is longer than the specified 250
Created a chunk of size 410, which is longer than the specified 250

[Document(page_content='3\tndm_002\tCU편의점(남대문로5가점)\t/smgis/ucimgs/conts/11103407/11103407_safe182_20211125152252_1.png\t서울특별시 중구 남대문로5가 84-6\t서울특별시 중구 세종대로 8-1\t[126.973355773,37.557595049]\t126.973355773\t37.557595049\t02-3789-6102\tNone\t1\tNone\thttps://www.safe182.go.kr/cont/homeLogContents.do?contentsNm=182_keeper_outline\t아동안전지킴이집 소개\t어린이 여러분!\n위험에 처했을 때 우리 동네에 있는 아동안전지킴이집을 확인하고 도움을 요청하세요.\n어린이 여러분의 안전을 지켜드리겠습니다.'),
 Document(page_content='3\tndm_002\tCU편의점(남대문로5가점)\t/smgis/ucimgs/conts/11103407/11103407_safe182_20211125152252_1.png\t서울특별시 중구 남대문로5가 84-6\t서울특별시 중구 세종대로 8-1\t[126.973355773,37.557595049]\t126.973355773\t37.557595049\t02-3789-6102\tNone\t1\tNone\thttps://www.safe182.go.kr/cont/homeLogContents.do?contentsNm=182_keeper_outline\t아동안전지킴이집 소개\t어린이 여러분!\n위험에 처했을 때 우리 동네에 있는 아동안전지킴이집을 확인하고 도움을 요청하세요.\n어린이 여러분의 안전을 지켜드리겠습니다.'),
 Document(page_content='1\t양천구_016\t목동카츠\t/smgis2/file/ucimgs/conts/1669595282433/성동구_014_1_KOR.jpg\t서울특별시 양천구 신정동 1008-16\t서울특별시 양천구 목동로9길 4\t[126.8641,37.52305]\t126.864100000\t37.523050000\t02-2039-0635\tNone\t1\tNone\tNone\t키즈메뉴(아이가먹을수있는 메뉴)\t등심돈가스, 우동, \n뽀로로어린이음료\t유아용품\t유아의자 1개\n포크수저세트\t영업시간\t평일, 주말, 공휴일\n11:30~21:30\t상세설명\t제주흑돼지 전문'),
 Document(page_content='1\t양천구_016\t목동카츠\t/smgis2/file/ucimgs/conts/1669595282433/성동구_014_1_KOR.jpg\t서울특별시 양천구 신정동 1008-16\t서울특별시 양천구 목동로9길 4\t[126.8641,37.52305]\t126.864100000\t37.523050000\t02-2039-0635\tNone\t1\tNone\tNone\t키즈메뉴(아이가먹을수있는 메뉴)\t등심돈가스, 우동, \n뽀로로어린이음료\t유아용품\t유아의자 1개\n포크수저세트\t영업시간\t평일, 주말, 공휴일\n11:30~21:30\t상세설명\t제주흑돼지 전문')]

In [31]:
db.get_context()

{'table_info': '\nCREATE TABLE gfdata."선거지도_21대총선_동" (\n\tfid INTEGER DEFAULT nextval(\'gfdata.l100005158_fid_seq\'::regclass) NOT NULL, \n\t"ADM_DR_CD" VARCHAR, \n\t"ADM_DR_NM" VARCHAR, \n\t"SIGUNGU_CD" VARCHAR, \n\t"SIDO_CD" VARCHAR, \n\t"DISTRICT" VARCHAR, \n\t"POP_VT" BIGINT, \n\t"SCS_CD" VARCHAR, \n\t"SCS_PRT" VARCHAR, \n\t"SIGUNGU_NM" VARCHAR, \n\t"SIDO_NM" VARCHAR, \n\t"ALIAS" VARCHAR\n)\n\n/*\n3 rows from 선거지도_21대총선_동 table:\nfid\tADM_DR_CD\tADM_DR_NM\tSIGUNGU_CD\tSIDO_CD\tDISTRICT\tPOP_VT\tSCS_CD\tSCS_PRT\tSIGUNGU_NM\tSIDO_NM\tALIAS\n1\t1101053\t사직동\t11010\t11\t종로구\t7751\t황교안\t미래통합당\t종로구\t서울특별시\t종로\n2\t1101054\t삼청동\t11010\t11\t종로구\t2237\t이낙연\t더불어민주당\t종로구\t서울특별시\t종로\n3\t1101055\t부암동\t11010\t11\t종로구\t7850\t이낙연\t더불어민주당\t종로구\t서울특별시\t종로\n*/\n\n\nCREATE TABLE gfdata.age_group_popltn (\n\tgid SERIAL NOT NULL, \n\t__gid VARCHAR(254), \n\ta_pre_a BIGINT, \n\ta_pre_m BIGINT, \n\ta_pre_f BIGINT, \n\ta_ele_a BIGINT, \n\ta_ele_m BIGINT, \n\ta_ele_f BIGINT, \n\ta_mid_a BIGINT, \n\ta_mid_m BIGINT, \n\ta_mid_f BIGINT, \n\ta_hig_a BIGINT, \n\ta_hig_m BIGINT, \n\ta_hig_f BIGINT, \n\ta_020_a BIGINT, \n\ta_020_m BIGINT, \n\ta_020_f BIGINT, \n\ta_030_a BIGINT, \n\ta_030_m BIGINT, \n\ta_030_f BIGINT, \n\ta_040_a BIGINT, \n\ta_040_m BIGINT, \n\ta_040_f BIGINT, \n\ta_050_a BIGINT, \n\ta_050_m BIGINT, \n\ta_050_f BIGINT, \n\ta_060_a BIGINT, \n\ta_060_m BIGINT, \n\ta_060_f BIGINT, \n\ta_070_a BIGINT, \n\ta_070_m BIGINT, \n\ta_070_f BIGINT, \n\ta_080_a BIGINT, \n\ta_080_m BIGINT, \n\ta_080_f BIGINT, \n\ta_090_a BIGINT, \n\ta_090_m BIGINT, \n\ta_090_f BIGINT, \n\ta_100_a BIGINT, \n\ta_100_m BIGINT, \n\ta_100_f BIGINT, \n\tsido_cd VARCHAR(10), \n\tsgg_cd VARCHAR(10), \n\tCONSTRAINT age_group_population_new_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from age_group_popltn table:\ngid\t__gid\ta_pre_a\ta_pre_m\ta_pre_f\ta_ele_a\ta_ele_m\ta_ele_f\ta_mid_a\ta_mid_m\ta_mid_f\ta_hig_a\ta_hig_m\ta_hig_f\ta_020_a\ta_020_m\ta_020_f\ta_030_a\ta_030_m\ta_030_f\ta_040_a\ta_040_m\ta_040_f\ta_050_a\ta_050_m\ta_050_f\ta_060_a\ta_060_m\ta_060_f\ta_070_a\ta_070_m\ta_070_f\ta_080_a\ta_080_m\ta_080_f\ta_090_a\ta_090_m\ta_090_f\ta_100_a\ta_100_m\ta_100_f\tsido_cd\tsgg_cd\n1\t다사613448\t6\t0\t0\t10\t9\t0\t8\t0\t0\t9\t6\t0\t26\t15\t11\t25\t14\t11\t19\t8\t11\t43\t23\t20\t37\t14\t23\t18\t11\t7\t10\t0\t8\t0\t0\t0\t0\t0\t0\t11\t230\n2\t다사583456\t6\t0\t0\t9\t6\t0\t0\t0\t0\t0\t0\t0\t76\t44\t32\t145\t72\t73\t92\t44\t48\t42\t20\t22\t33\t14\t19\t20\t10\t10\t7\t0\t0\t0\t0\t0\t0\t0\t0\t11\t230\n3\t다사597458\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t16\t9\t7\t10\t8\t0\t0\t0\t0\t17\t9\t8\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t11\t230\n*/\n\n\nCREATE TABLE gfdata.al_11_d010_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_11_d010_new_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_11_d010_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n13696384\t32\t1991201839054527769900000000\t1111017500107040000\t1111017500\t서울특별시 종로구 숭인동\t704\t1\t일반\t01000\t단독주택\t39\t기타강구조\t57.6\t1991-09-02\t203.13\t100.6\t9.1\t57.26\t144.66202\t29692\tN\tB00100000000T30Z9\t2024-05-01\t11110\tNone\tNone\t3\t0\t2017-05-30\n13696385\t34\t1967201343844527773800000000\t1111017500100560024\t1111017500\t서울특별시 종로구 숭인동\t56-24\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1967-05-28\t114.98\t0.0\t0.0\t0.0\t0.0\t12540\tN\tB00100000000T311B\t2024-05-01\t11110\tNone\tNone\t3\t0\t2018-06-19\n13696386\t36\t1962201375194527742000000000\t1111017500100560054\t1111017500\t서울특별시 종로구 숭인동\t56-54\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1962-12-21\t135.2\t0.0\t0.0\t0.0\t0.0\t24867\tN\tB00100000000T313D\t2024-05-01\t11110\tNone\tNone\t2\t0\t2017-02-24\n*/\n\n\nCREATE TABLE gfdata.al_11_d010_new_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_11_d010_new_new_40_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_11_d010_new_202403 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n13696326\t32\t1991201839054527769900000000\t1111017500107040000\t1111017500\t서울특별시 종로구 숭인동\t704\t1\t일반\t01000\t단독주택\t39\t기타강구조\t57.6\t1991-09-02\t203.13\t100.6\t9.1\t57.26\t144.66202\t29692\tN\tB00100000000T30Z9\t2024-04-01\t11110\tNone\tNone\t3\t0\t2017-05-30\n13696327\t34\t1967201343844527773800000000\t1111017500100560024\t1111017500\t서울특별시 종로구 숭인동\t56-24\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1967-05-28\t114.98\t0.0\t0.0\t0.0\t0.0\t12540\tN\tB00100000000T311B\t2024-04-01\t11110\tNone\tNone\t3\t0\t2018-06-19\n13696328\t36\t1962201375194527742000000000\t1111017500100560054\t1111017500\t서울특별시 종로구 숭인동\t56-54\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1962-12-21\t135.2\t0.0\t0.0\t0.0\t0.0\t24867\tN\tB00100000000T313D\t2024-04-01\t11110\tNone\tNone\t2\t0\t2017-02-24\n*/\n\n\nCREATE TABLE gfdata.al_11_d010_new_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_11_d010_new_new_45_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_11_d010_new_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n13696373\t32\t1991201839054527769900000000\t1111017500107040000\t1111017500\t서울특별시 종로구 숭인동\t704\t1\t일반\t01000\t단독주택\t39\t기타강구조\t57.6\t1991-09-02\t203.13\t100.6\t9.1\t57.26\t144.66202\t29692\tN\tB00100000000T30Z9\t2024-06-04\t11110\tNone\tNone\t3\t0\t2017-05-30\n13696374\t34\t1967201343844527773800000000\t1111017500100560024\t1111017500\t서울특별시 종로구 숭인동\t56-24\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1967-05-28\t114.98\t0.0\t0.0\t0.0\t0.0\t12540\tN\tB00100000000T311B\t2024-06-04\t11110\tNone\tNone\t3\t0\t2018-06-19\n13696375\t36\t1962201375194527742000000000\t1111017500100560054\t1111017500\t서울특별시 종로구 숭인동\t56-54\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1962-12-21\t135.2\t0.0\t0.0\t0.0\t0.0\t24867\tN\tB00100000000T313D\t2024-06-04\t11110\tNone\tNone\t2\t0\t2017-02-24\n*/\n\n\nCREATE TABLE gfdata.al_26_d010 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_26_d010_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_26_d010 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n11513932\t223\t1998202070161786836800000000\t2611012000100160026\t2611012000\t부산광역시 중구 보수동1가\t16-26\t1\t일반\t02000\t공동주택\t21\t철근콘크리트구조\t57.74\t1998-05-01\t230.96\t69.2\t11.95\t83.44\t333.76\t7759\tN\tB0010000000B0N8EX\t2024-05-01\t26110\tNone\tNone\t4\t0\t2011-01-13\n11513933\t484\t1978201965801784846100000000\t2611012200100090004\t2611012200\t부산광역시 중구 보수동3가\t9-4\t1\t일반\t01000\t단독주택\t12\t블록구조\t52.2\t1978-01-23\t78.38\t0.0\t0.0\t0.0\t0.0\t8549\tN\tB0010000000B0QGNI\t2024-05-01\t26110\tNone\tNone\t2\t0\t2017-11-02\n11513934\t225\t1992202154291786601000000000\t2611012000100330016\t2611012000\t부산광역시 중구 보수동1가\t33-16\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t60.13\t1992-10-12\t199.74\t113.56\t6.96\t52.95\t103.62\t6618\tN\tB0010000000B0U6XM\t2024-05-01\t26110\tNone\tNone\t2\t1\t2011-01-13\n*/\n\n\nCREATE TABLE gfdata.al_26_d010_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_26_d010_new_40_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_26_d010_202403 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n11514134\t223\t1998202070161786836800000000\t2611012000100160026\t2611012000\t부산광역시 중구 보수동1가\t16-26\t1\t일반\t02000\t공동주택\t21\t철근콘크리트구조\t57.74\t1998-05-01\t230.96\t69.2\t11.95\t83.44\t333.76\t7759\tN\tB0010000000B0N8EX\t2024-04-01\t26110\tNone\tNone\t4\t0\t2011-01-13\n11514135\t484\t1978201965801784846100000000\t2611012200100090004\t2611012200\t부산광역시 중구 보수동3가\t9-4\t1\t일반\t01000\t단독주택\t12\t블록구조\t52.2\t1978-01-23\t78.38\t0.0\t0.0\t0.0\t0.0\t8549\tN\tB0010000000B0QGNI\t2024-04-01\t26110\tNone\tNone\t2\t0\t2017-11-02\n11514136\t225\t1992202154291786601000000000\t2611012000100330016\t2611012000\t부산광역시 중구 보수동1가\t33-16\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t60.13\t1992-10-12\t199.74\t113.56\t6.96\t52.95\t103.62\t6618\tN\tB0010000000B0U6XM\t2024-04-01\t26110\tNone\tNone\t2\t1\t2011-01-13\n*/\n\n\nCREATE TABLE gfdata.al_26_d010_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_26_d010_new_45_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_26_d010_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n11513671\t223\t1998202070161786836800000000\t2611012000100160026\t2611012000\t부산광역시 중구 보수동1가\t16-26\t1\t일반\t02000\t공동주택\t21\t철근콘크리트구조\t57.74\t1998-05-01\t230.96\t69.2\t11.95\t83.44\t333.76\t7759\tN\tB0010000000B0N8EX\t2024-06-04\t26110\tNone\tNone\t4\t0\t2011-01-13\n11513672\t484\t1978201965801784846100000000\t2611012200100090004\t2611012200\t부산광역시 중구 보수동3가\t9-4\t1\t일반\t01000\t단독주택\t12\t블록구조\t52.2\t1978-01-23\t78.38\t0.0\t0.0\t0.0\t0.0\t8549\tN\tB0010000000B0QGNI\t2024-06-04\t26110\tNone\tNone\t2\t0\t2017-11-02\n11513673\t225\t1992202154291786601000000000\t2611012000100330016\t2611012000\t부산광역시 중구 보수동1가\t33-16\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t60.13\t1992-10-12\t199.74\t113.56\t6.96\t52.95\t103.62\t6618\tN\tB0010000000B0U6XM\t2024-06-04\t26110\tNone\tNone\t2\t1\t2011-01-13\n*/\n\n\nCREATE TABLE gfdata.al_27_d010 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_27_d010_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_27_d010 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10756935\t46627\t1949163376372622421000000000\t2711015600107350049\t2711015600\t대구광역시 중구 남산동\t735-49\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1949-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-05-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756936\t36767\t0000163261862627417000000000\t2711015600109210027\t2711015600\t대구광역시 중구 남산동\t921-27\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-05-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756937\t35691\t1967162308722621416300000000\t2711015600124210007\t2711015600\t대구광역시 중구 남산동\t2421-7\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1967-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-05-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n*/\n\n\nCREATE TABLE gfdata.al_27_d010_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_27_d010_new_40_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_27_d010_202403 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10756974\t46627\t1949163376372622421000000000\t2711015600107350049\t2711015600\t대구광역시 중구 남산동\t735-49\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1949-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-04-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756975\t36767\t0000163261862627417000000000\t2711015600109210027\t2711015600\t대구광역시 중구 남산동\t921-27\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-04-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756976\t35691\t1967162308722621416300000000\t2711015600124210007\t2711015600\t대구광역시 중구 남산동\t2421-7\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1967-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-04-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n*/\n\n\nCREATE TABLE gfdata.al_27_d010_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_27_d010_new_45_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_27_d010_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10756939\t46627\t1949163376372622421000000000\t2711015600107350049\t2711015600\t대구광역시 중구 남산동\t735-49\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1949-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-06-04\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756940\t36767\t0000163261862627417000000000\t2711015600109210027\t2711015600\t대구광역시 중구 남산동\t921-27\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-06-04\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756941\t35691\t1967162308722621416300000000\t2711015600124210007\t2711015600\t대구광역시 중구 남산동\t2421-7\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1967-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-06-04\t27110\tNone\tNone\t0\t0\t2010-01-19\n*/\n\n\nCREATE TABLE gfdata.al_28_d010 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_28_d010_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_28_d010 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10460910\t69\t0000147661854315781200000000\t2811015200201890000\t2811015200\t인천광역시 중구 무의동\t189\t2\t산\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tB00100000001AV3E1\t2024-05-01\t28110\tNone\tNone\t0\t0\t2011-11-16\n10460911\t70\t0000147663704315722500000000\t2811015200201890000\t2811015200\t인천광역시 중구 무의동\t189\t2\t산\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tB00100000001AV3F2\t2024-05-01\t28110\tNone\tNone\t0\t0\t2011-11-16\n10460912\t72\t0000147958424314062300000000\t2811015200100800001\t2811015200\t인천광역시 중구 무의동\t80-1\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tB00100000001AV7D4\t2024-05-01\t28110\tNone\tNone\t0\t0\t2011-11-16\n*/\n\n\nCREATE TABLE gfdata.al_28_d010_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VA

In [22]:
db.get_context()['table_info']

'\nCREATE TABLE gfdata."선거지도_21대총선_동" (\n\tfid INTEGER DEFAULT nextval(\'gfdata.l100005158_fid_seq\'::regclass) NOT NULL, \n\t"ADM_DR_CD" VARCHAR, \n\t"ADM_DR_NM" VARCHAR, \n\t"SIGUNGU_CD" VARCHAR, \n\t"SIDO_CD" VARCHAR, \n\t"DISTRICT" VARCHAR, \n\t"POP_VT" BIGINT, \n\t"SCS_CD" VARCHAR, \n\t"SCS_PRT" VARCHAR, \n\t"SIGUNGU_NM" VARCHAR, \n\t"SIDO_NM" VARCHAR, \n\t"ALIAS" VARCHAR\n)\n\n/*\n3 rows from 선거지도_21대총선_동 table:\nfid\tADM_DR_CD\tADM_DR_NM\tSIGUNGU_CD\tSIDO_CD\tDISTRICT\tPOP_VT\tSCS_CD\tSCS_PRT\tSIGUNGU_NM\tSIDO_NM\tALIAS\n1\t1101053\t사직동\t11010\t11\t종로구\t7751\t황교안\t미래통합당\t종로구\t서울특별시\t종로\n2\t1101054\t삼청동\t11010\t11\t종로구\t2237\t이낙연\t더불어민주당\t종로구\t서울특별시\t종로\n3\t1101055\t부암동\t11010\t11\t종로구\t7850\t이낙연\t더불어민주당\t종로구\t서울특별시\t종로\n*/\n\n\nCREATE TABLE gfdata.age_group_popltn (\n\tgid SERIAL NOT NULL, \n\t__gid VARCHAR(254), \n\ta_pre_a BIGINT, \n\ta_pre_m BIGINT, \n\ta_pre_f BIGINT, \n\ta_ele_a BIGINT, \n\ta_ele_m BIGINT, \n\ta_ele_f BIGINT, \n\ta_mid_a BIGINT, \n\ta_mid_m BIGINT, \n\ta_mid_f BIGINT, \n\ta_hig_a BIGINT, \n\ta_hig_m BIGINT, \n\ta_hig_f BIGINT, \n\ta_020_a BIGINT, \n\ta_020_m BIGINT, \n\ta_020_f BIGINT, \n\ta_030_a BIGINT, \n\ta_030_m BIGINT, \n\ta_030_f BIGINT, \n\ta_040_a BIGINT, \n\ta_040_m BIGINT, \n\ta_040_f BIGINT, \n\ta_050_a BIGINT, \n\ta_050_m BIGINT, \n\ta_050_f BIGINT, \n\ta_060_a BIGINT, \n\ta_060_m BIGINT, \n\ta_060_f BIGINT, \n\ta_070_a BIGINT, \n\ta_070_m BIGINT, \n\ta_070_f BIGINT, \n\ta_080_a BIGINT, \n\ta_080_m BIGINT, \n\ta_080_f BIGINT, \n\ta_090_a BIGINT, \n\ta_090_m BIGINT, \n\ta_090_f BIGINT, \n\ta_100_a BIGINT, \n\ta_100_m BIGINT, \n\ta_100_f BIGINT, \n\tsido_cd VARCHAR(10), \n\tsgg_cd VARCHAR(10), \n\tCONSTRAINT age_group_population_new_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from age_group_popltn table:\ngid\t__gid\ta_pre_a\ta_pre_m\ta_pre_f\ta_ele_a\ta_ele_m\ta_ele_f\ta_mid_a\ta_mid_m\ta_mid_f\ta_hig_a\ta_hig_m\ta_hig_f\ta_020_a\ta_020_m\ta_020_f\ta_030_a\ta_030_m\ta_030_f\ta_040_a\ta_040_m\ta_040_f\ta_050_a\ta_050_m\ta_050_f\ta_060_a\ta_060_m\ta_060_f\ta_070_a\ta_070_m\ta_070_f\ta_080_a\ta_080_m\ta_080_f\ta_090_a\ta_090_m\ta_090_f\ta_100_a\ta_100_m\ta_100_f\tsido_cd\tsgg_cd\n1\t다사613448\t6\t0\t0\t10\t9\t0\t8\t0\t0\t9\t6\t0\t26\t15\t11\t25\t14\t11\t19\t8\t11\t43\t23\t20\t37\t14\t23\t18\t11\t7\t10\t0\t8\t0\t0\t0\t0\t0\t0\t11\t230\n2\t다사583456\t6\t0\t0\t9\t6\t0\t0\t0\t0\t0\t0\t0\t76\t44\t32\t145\t72\t73\t92\t44\t48\t42\t20\t22\t33\t14\t19\t20\t10\t10\t7\t0\t0\t0\t0\t0\t0\t0\t0\t11\t230\n3\t다사597458\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t16\t9\t7\t10\t8\t0\t0\t0\t0\t17\t9\t8\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t11\t230\n*/\n\n\nCREATE TABLE gfdata.al_11_d010_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_11_d010_new_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_11_d010_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n13696384\t32\t1991201839054527769900000000\t1111017500107040000\t1111017500\t서울특별시 종로구 숭인동\t704\t1\t일반\t01000\t단독주택\t39\t기타강구조\t57.6\t1991-09-02\t203.13\t100.6\t9.1\t57.26\t144.66202\t29692\tN\tB00100000000T30Z9\t2024-05-01\t11110\tNone\tNone\t3\t0\t2017-05-30\n13696385\t34\t1967201343844527773800000000\t1111017500100560024\t1111017500\t서울특별시 종로구 숭인동\t56-24\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1967-05-28\t114.98\t0.0\t0.0\t0.0\t0.0\t12540\tN\tB00100000000T311B\t2024-05-01\t11110\tNone\tNone\t3\t0\t2018-06-19\n13696386\t36\t1962201375194527742000000000\t1111017500100560054\t1111017500\t서울특별시 종로구 숭인동\t56-54\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1962-12-21\t135.2\t0.0\t0.0\t0.0\t0.0\t24867\tN\tB00100000000T313D\t2024-05-01\t11110\tNone\tNone\t2\t0\t2017-02-24\n*/\n\n\nCREATE TABLE gfdata.al_11_d010_new_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_11_d010_new_new_40_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_11_d010_new_202403 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n13696326\t32\t1991201839054527769900000000\t1111017500107040000\t1111017500\t서울특별시 종로구 숭인동\t704\t1\t일반\t01000\t단독주택\t39\t기타강구조\t57.6\t1991-09-02\t203.13\t100.6\t9.1\t57.26\t144.66202\t29692\tN\tB00100000000T30Z9\t2024-04-01\t11110\tNone\tNone\t3\t0\t2017-05-30\n13696327\t34\t1967201343844527773800000000\t1111017500100560024\t1111017500\t서울특별시 종로구 숭인동\t56-24\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1967-05-28\t114.98\t0.0\t0.0\t0.0\t0.0\t12540\tN\tB00100000000T311B\t2024-04-01\t11110\tNone\tNone\t3\t0\t2018-06-19\n13696328\t36\t1962201375194527742000000000\t1111017500100560054\t1111017500\t서울특별시 종로구 숭인동\t56-54\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1962-12-21\t135.2\t0.0\t0.0\t0.0\t0.0\t24867\tN\tB00100000000T313D\t2024-04-01\t11110\tNone\tNone\t2\t0\t2017-02-24\n*/\n\n\nCREATE TABLE gfdata.al_11_d010_new_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_11_d010_new_new_45_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_11_d010_new_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n13696373\t32\t1991201839054527769900000000\t1111017500107040000\t1111017500\t서울특별시 종로구 숭인동\t704\t1\t일반\t01000\t단독주택\t39\t기타강구조\t57.6\t1991-09-02\t203.13\t100.6\t9.1\t57.26\t144.66202\t29692\tN\tB00100000000T30Z9\t2024-06-04\t11110\tNone\tNone\t3\t0\t2017-05-30\n13696374\t34\t1967201343844527773800000000\t1111017500100560024\t1111017500\t서울특별시 종로구 숭인동\t56-24\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1967-05-28\t114.98\t0.0\t0.0\t0.0\t0.0\t12540\tN\tB00100000000T311B\t2024-06-04\t11110\tNone\tNone\t3\t0\t2018-06-19\n13696375\t36\t1962201375194527742000000000\t1111017500100560054\t1111017500\t서울특별시 종로구 숭인동\t56-54\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t0.0\t1962-12-21\t135.2\t0.0\t0.0\t0.0\t0.0\t24867\tN\tB00100000000T313D\t2024-06-04\t11110\tNone\tNone\t2\t0\t2017-02-24\n*/\n\n\nCREATE TABLE gfdata.al_26_d010 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_26_d010_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_26_d010 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n11513932\t223\t1998202070161786836800000000\t2611012000100160026\t2611012000\t부산광역시 중구 보수동1가\t16-26\t1\t일반\t02000\t공동주택\t21\t철근콘크리트구조\t57.74\t1998-05-01\t230.96\t69.2\t11.95\t83.44\t333.76\t7759\tN\tB0010000000B0N8EX\t2024-05-01\t26110\tNone\tNone\t4\t0\t2011-01-13\n11513933\t484\t1978201965801784846100000000\t2611012200100090004\t2611012200\t부산광역시 중구 보수동3가\t9-4\t1\t일반\t01000\t단독주택\t12\t블록구조\t52.2\t1978-01-23\t78.38\t0.0\t0.0\t0.0\t0.0\t8549\tN\tB0010000000B0QGNI\t2024-05-01\t26110\tNone\tNone\t2\t0\t2017-11-02\n11513934\t225\t1992202154291786601000000000\t2611012000100330016\t2611012000\t부산광역시 중구 보수동1가\t33-16\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t60.13\t1992-10-12\t199.74\t113.56\t6.96\t52.95\t103.62\t6618\tN\tB0010000000B0U6XM\t2024-05-01\t26110\tNone\tNone\t2\t1\t2011-01-13\n*/\n\n\nCREATE TABLE gfdata.al_26_d010_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_26_d010_new_40_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_26_d010_202403 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n11514134\t223\t1998202070161786836800000000\t2611012000100160026\t2611012000\t부산광역시 중구 보수동1가\t16-26\t1\t일반\t02000\t공동주택\t21\t철근콘크리트구조\t57.74\t1998-05-01\t230.96\t69.2\t11.95\t83.44\t333.76\t7759\tN\tB0010000000B0N8EX\t2024-04-01\t26110\tNone\tNone\t4\t0\t2011-01-13\n11514135\t484\t1978201965801784846100000000\t2611012200100090004\t2611012200\t부산광역시 중구 보수동3가\t9-4\t1\t일반\t01000\t단독주택\t12\t블록구조\t52.2\t1978-01-23\t78.38\t0.0\t0.0\t0.0\t0.0\t8549\tN\tB0010000000B0QGNI\t2024-04-01\t26110\tNone\tNone\t2\t0\t2017-11-02\n11514136\t225\t1992202154291786601000000000\t2611012000100330016\t2611012000\t부산광역시 중구 보수동1가\t33-16\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t60.13\t1992-10-12\t199.74\t113.56\t6.96\t52.95\t103.62\t6618\tN\tB0010000000B0U6XM\t2024-04-01\t26110\tNone\tNone\t2\t1\t2011-01-13\n*/\n\n\nCREATE TABLE gfdata.al_26_d010_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_26_d010_new_45_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_26_d010_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n11513671\t223\t1998202070161786836800000000\t2611012000100160026\t2611012000\t부산광역시 중구 보수동1가\t16-26\t1\t일반\t02000\t공동주택\t21\t철근콘크리트구조\t57.74\t1998-05-01\t230.96\t69.2\t11.95\t83.44\t333.76\t7759\tN\tB0010000000B0N8EX\t2024-06-04\t26110\tNone\tNone\t4\t0\t2011-01-13\n11513672\t484\t1978201965801784846100000000\t2611012200100090004\t2611012200\t부산광역시 중구 보수동3가\t9-4\t1\t일반\t01000\t단독주택\t12\t블록구조\t52.2\t1978-01-23\t78.38\t0.0\t0.0\t0.0\t0.0\t8549\tN\tB0010000000B0QGNI\t2024-06-04\t26110\tNone\tNone\t2\t0\t2017-11-02\n11513673\t225\t1992202154291786601000000000\t2611012000100330016\t2611012000\t부산광역시 중구 보수동1가\t33-16\t1\t일반\t01000\t단독주택\t11\t벽돌구조\t60.13\t1992-10-12\t199.74\t113.56\t6.96\t52.95\t103.62\t6618\tN\tB0010000000B0U6XM\t2024-06-04\t26110\tNone\tNone\t2\t1\t2011-01-13\n*/\n\n\nCREATE TABLE gfdata.al_27_d010 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_27_d010_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_27_d010 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10756935\t46627\t1949163376372622421000000000\t2711015600107350049\t2711015600\t대구광역시 중구 남산동\t735-49\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1949-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-05-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756936\t36767\t0000163261862627417000000000\t2711015600109210027\t2711015600\t대구광역시 중구 남산동\t921-27\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-05-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756937\t35691\t1967162308722621416300000000\t2711015600124210007\t2711015600\t대구광역시 중구 남산동\t2421-7\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1967-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-05-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n*/\n\n\nCREATE TABLE gfdata.al_27_d010_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_27_d010_new_40_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_27_d010_202403 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10756974\t46627\t1949163376372622421000000000\t2711015600107350049\t2711015600\t대구광역시 중구 남산동\t735-49\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1949-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-04-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756975\t36767\t0000163261862627417000000000\t2711015600109210027\t2711015600\t대구광역시 중구 남산동\t921-27\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-04-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756976\t35691\t1967162308722621416300000000\t2711015600124210007\t2711015600\t대구광역시 중구 남산동\t2421-7\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1967-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-04-01\t27110\tNone\tNone\t0\t0\t2010-01-19\n*/\n\n\nCREATE TABLE gfdata.al_27_d010_new (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_27_d010_new_45_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_27_d010_new table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10756939\t46627\t1949163376372622421000000000\t2711015600107350049\t2711015600\t대구광역시 중구 남산동\t735-49\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1949-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-06-04\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756940\t36767\t0000163261862627417000000000\t2711015600109210027\t2711015600\t대구광역시 중구 남산동\t921-27\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-06-04\t27110\tNone\tNone\t0\t0\t2010-01-19\n10756941\t35691\t1967162308722621416300000000\t2711015600124210007\t2711015600\t대구광역시 중구 남산동\t2421-7\t1\t일반\tNone\tNone\tNone\tNone\t0.0\t1967-01-01\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tNone\t2024-06-04\t27110\tNone\tNone\t0\t0\t2010-01-19\n*/\n\n\nCREATE TABLE gfdata.al_28_d010 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\ta26 INTEGER, \n\ta27 INTEGER, \n\ta28 VARCHAR(10), \n\tCONSTRAINT al_28_d010_new_33_pkey PRIMARY KEY (gid)\n)\n\n/*\n3 rows from al_28_d010 table:\ngid\ta0\ta1\ta2\ta3\ta4\ta5\ta6\ta7\ta8\ta9\ta10\ta11\ta12\ta13\ta14\ta15\ta16\ta17\ta18\ta19\ta20\ta21\ta22\ta23\ta24\ta25\ta26\ta27\ta28\n10460910\t69\t0000147661854315781200000000\t2811015200201890000\t2811015200\t인천광역시 중구 무의동\t189\t2\t산\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tB00100000001AV3E1\t2024-05-01\t28110\tNone\tNone\t0\t0\t2011-11-16\n10460911\t70\t0000147663704315722500000000\t2811015200201890000\t2811015200\t인천광역시 중구 무의동\t189\t2\t산\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tB00100000001AV3F2\t2024-05-01\t28110\tNone\tNone\t0\t0\t2011-11-16\n10460912\t72\t0000147958424314062300000000\t2811015200100800001\t2811015200\t인천광역시 중구 무의동\t80-1\t1\t일반\tNone\tNone\tNone\tNone\t0.0\tNone\t0.0\t0.0\t0.0\t0.0\t0.0\tNone\tNone\tB00100000001AV7D4\t2024-05-01\t28110\tNone\tNone\t0\t0\t2011-11-16\n*/\n\n\nCREATE TABLE gfdata.al_28_d010_202403 (\n\tgid SERIAL NOT NULL, \n\ta0 INTEGER, \n\ta1 VARCHAR(28), \n\ta2 VARCHAR(19), \n\ta3 VARCHAR(10), \n\ta4 VARCHAR(254), \n\ta5 VARCHAR(10), \n\ta6 VARCHAR(1), \n\ta7 VARCHAR(254), \n\ta8 VARCHAR(5), \n\ta9 VARCHAR(254), \n\ta10 VARCHAR(2), \n\ta11 VARCHAR(254), \n\ta12 DOUBLE PRECISION, \n\ta13 VARCHAR(10), \n\ta14 DOUBLE PRECISION, \n\ta15 DOUBLE PRECISION, \n\ta16 DOUBLE PRECISION, \n\ta17 DOUBLE PRECISION, \n\ta18 DOUBLE PRECISION, \n\ta19 VARCHAR(28), \n\ta20 VARCHAR(2), \n\ta21 VARCHAR(17), \n\ta22 DATE, \n\ta23 VARCHAR(5), \n\ta24 VARCHAR(254), \n\ta25 VARCHAR(254), \n\

# 로컬모델을 이용하더라도 프롬프토 조작을 통해 원하는 답변 얻을 수 있음

# LangSmith 추적을 통해 이 체인이 무엇을 하는지 더 잘 이해할 수 있습니다. 또한 체인의 프롬프트를 직접 검사할 수도 있습니다. 아래의 프롬프트를 보면 다음과 같습니다:

- 방언 특정입니다. 이 경우에는 SQLite를 명시적으로 참조합니다.
- 사용 가능한 모든 테이블에 대한 정의가 있습니다.
- 각 테이블에 대해 세 개의 예제 행이 있습니다.
- 이 기술은 예제 행을 보여주고 테이블에 대해 명시적으로 설명하는 것이 성능을 향상시킨다고 제안하는 논문에서 영감을 받았습니다. 전체 프롬프트를 다음과 같이 검사할 수도 있습니다:

LangChain docs 와는 달리 아래 prompt와 inputs를 사용, llama-3 기반 오픈
모델으로도 쿼리 생성 및 실행 가능
---------------------------
- prompt(hub.pull("rlm/text-to-sql"))
- inputs = {
    "table_info": lambda x: db.get_table_info(),
    "input": lambda x: x["question"],
    "few_shot_examples": lambda x: "",
    "dialect": lambda x: db.dialect,
}
-----------------------------

# 쿼리 실행기 추가
- QuerySQLDataBaseTool을 Chain에 넣어 생성된 sql query를 곧바로 실행할 수 있음.

In [11]:
from langchain_community.tools import QuerySQLDataBaseTool

execute_query = QuerySQLDataBaseTool(db = db)

query = '''선거와 관련된 테이블을 선택하고 테이블의 행정동 갯수를 알려줘?'''
response = sql_response

chain = response | execute_query
chain.invoke({'question': f'{query}'})

SQLQuery: SELECT COUNT(*) FROM z_sop_bnd_adm_dong_pg;

'[(3528,)]'

# 질문에 답하기
- 이제 자동으로 SQL 쿼리를 생성하고 실행하는 방법을 갖추었으므로, 원래의 질문과 SQL 쿼리 결과를 결합하여 최종 답변을 생성하기만 하면 됩니다. 이를 위해 질문과 결과를 다시 LLM에 전달할 수 있습니다:

In [15]:
from operator import itemgetter

from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough

# answer_prompt = PromptTemplate.from_template(
#     """Given the following user question, corresponding SQL query, and SQL result, answer the user question.

# Question: {question}
# SQL Query: {query}
# SQL Result: {result}
# Answer: """
# )

# answer = answer_prompt | llm | StrOutputParser()
# chain = (
#     RunnablePassthrough.assign(query=response).assign(
#         result=itemgetter("query") | execute_query
#     )
#     | answer
# )

# chain.invoke({"question": "How many employees are there"})

SQLQuery: SELECT COUNT(*) FROM Employee;
8명의 직원이 있습니다.

'8명의 직원이 있습니다.'

# Chain을 구성하는 방법 외에 agent를 구성하는 방법도 있습니다

LangChain에는 SQL 데이터베이스와 상호 작용하는 더 유연한 방법을 제공하는 SQL 에이전트가 있습니다. SQL 에이전트를 사용하는 주요 장점은 다음과 같습니다:
 
- 데이터베이스의 스키마뿐만 아니라 데이터베이스의 내용(특정 테이블 설명 등)을 기반으로 질문에 답할 수 있습니다.
- 생성된 쿼리를 실행하고 트레이스백을 잡아 올바르게 재생성하여 오류에서 복구할 수 있습니다.
- 여러 종속 쿼리가 필요한 질문에 답할 수 있습니다.
- 관련 테이블의 스키마만 고려하여 토큰을 절약할 수 있습니다.
- 에이전트를 초기화하려면 create_sql_agent 함수를 사용합니다. 이 에이전트에는 다음과 같은 도구를 포함하는 SQLDatabaseToolkit이 포함되어 있습니다:
 
- 쿼리 생성 및 실행
- 쿼리 구문 검사
- 테이블 설명 검색

In [1]:
from langchain_community.agent_toolkits import create_sql_agent

json_prompt_ko = hub.pull('teddynote/react-chat-json-korean')

llama_3_agent = create_json_chat_agent(llama3, tools, json_prompt_ko) #xionic-ko-llama-3-70b 사용

########## 5. AgentExecutor 를 정의합니다 ##########

# AgentExecutor 클래스를 사용하여 agent와 tools를 설정하고, 상세한 로그를 출력하도록 verbose를 True로 설정합니다.
agent_executor = AgentExecutor(agent=llama_3_agent, tools=tools, verbose=True)

########## 6. 채팅 기록을 수행하는 메모리를 추가합니다. ##########

# 채팅 메시지 기록을 관리하는 객체를 생성합니다.
message_history = ChatMessageHistory()

# 채팅 메시지 기록이 추가된 에이전트를 생성합니다.
agent_with_chat_history = RunnableWithMessageHistory(
    agent_executor,
    # 대부분의 실제 시나리오에서 세션 ID가 필요하기 때문에 이것이 필요합니다
    # 여기서는 간단한 메모리 내 ChatMessageHistory를 사용하기 때문에 실제로 사용되지 않습니다
    lambda session_id: message_history,
    # 프롬프트의 질문이 입력되는 key: "input"
    input_messages_key="input",
    # 프롬프트의 메시지가 입력되는 key: "chat_history"
    history_messages_key="chat_history",
)




llama_3_agent = create_json_chat_agent(llama3, tools, json_prompt_ko) #xionic-ko-llama-3-70b 사용

########## 5. AgentExecutor 를 정의합니다 ##########

# AgentExecutor 클래스를 사용하여 agent와 tools를 설정하고, 상세한 로그를 출력하도록 verbose를 True로 설정합니다.
agent_executor = AgentExecutor(agent=llama_3_agent, tools=tools, verbose=True)
agent_executor = create_sql_agent(llm=llm, db=db, agent_type="openai-tools", verbose=True)

NameError: name 'ChatOpenAI' is not defined

In [26]:
agent_executor.invoke(
    {
        "input": "List the total sales per all countries. Which country's customers spent the most?"
    }
)

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with `{}`


Album, Artist, Customer, Employee, Genre, Invoice, InvoiceLine, MediaType, Playlist, PlaylistTrack, Track
Invoking: `sql_db_schema` with `{'table_names': 'Customer, Invoice, InvoiceLine'}`



CREATE TABLE "Customer" (
	"CustomerId" INTEGER NOT NULL,
	"FirstName" NVARCHAR(40) NOT NULL,
	"LastName" NVARCHAR(20) NOT NULL,
	"Company" NVARCHAR(80),
	"Address" NVARCHAR(70),
	"City" NVARCHAR(40),
	"State" NVARCHAR(40),
	"Country" NVARCHAR(40),
	"PostalCode" NVARCHAR(10),
	"Phone" NVARCHAR(24),
	"Fax" NVARCHAR(24),
	"Email" NVARCHAR(60) NOT NULL,
	"SupportRepId" INTEGER,
	PRIMARY KEY ("CustomerId"),
	FOREIGN KEY("SupportRepId") REFERENCES "Employee" ("EmployeeId")
)

/*
3 rows from Customer table:
CustomerId	FirstName	LastName	Company	Address	City	State	Country	PostalCode	Phone	Fax	Email	SupportRepId
1	Luís	Gonçalves	Embraer - Empresa Brasileira de Aeronáutica S.A.	Av. Brigadeiro Faria Lima, 2170	São José dos Campos	SP	Brazil	12227-000	+55 (12) 3923-5555	+55 (12) 3923-5566	luisg@embraer.com.br	3
2	Leonie	Köhler	None	Theodor-Heuss-Straße 34	Stuttgart	None	Germany	70174	+49 0711 2842222	None	leonekohler@surfeu.de	5
3	François	Tremblay	None	1498 rue Bélanger	Montréal	QC	Canada	H2G 1A7	+1 (514) 721-4711	None	ftremblay@gmail.com	3
*/


CREATE TABLE "Invoice" (
	"InvoiceId" INTEGER NOT NULL,
	"CustomerId" INTEGER NOT NULL,
	"InvoiceDate" DATETIME NOT NULL,
	"BillingAddress" NVARCHAR(70),
	"BillingCity" NVARCHAR(40),
	"BillingState" NVARCHAR(40),
	"BillingCountry" NVARCHAR(40),
	"BillingPostalCode" NVARCHAR(10),
	"Total" NUMERIC(10, 2) NOT NULL,
	PRIMARY KEY ("InvoiceId"),
	FOREIGN KEY("CustomerId") REFERENCES "Customer" ("CustomerId")
)

/*
3 rows from Invoice table:
InvoiceId	CustomerId	InvoiceDate	BillingAddress	BillingCity	BillingState	BillingCountry	BillingPostalCode	Total
1	2	2021-01-01 00:00:00	Theodor-Heuss-Straße 34	Stuttgart	None	Germany	70174	1.98
2	4	2021-01-02 00:00:00	Ullevålsveien 14	Oslo	None	Norway	0171	3.96
3	8	2021-01-03 00:00:00	Grétrystraat 63	Brussels	None	Belgium	1000	5.94
*/


CREATE TABLE "InvoiceLine" (
	"InvoiceLineId" INTEGER NOT NULL,
	"InvoiceId" INTEGER NOT NULL,
	"TrackId" INTEGER NOT NULL,
	"UnitPrice" NUMERIC(10, 2) NOT NULL,
	"Quantity" INTEGER NOT NULL,
	PRIMARY KEY ("InvoiceLineId"),
	FOREIGN KEY("TrackId") REFERENCES "Track" ("TrackId"),
	FOREIGN KEY("InvoiceId") REFERENCES "Invoice" ("InvoiceId")
)

/*
3 rows from InvoiceLine table:
InvoiceLineId	InvoiceId	TrackId	UnitPrice	Quantity
1	1	2	0.99	1
2	1	4	0.99	1
3	2	6	0.99	1
*/
Invoking: `sql_db_query` with `{'query': 'SELECT BillingCountry AS Country, SUM(Total) AS TotalSales FROM Invoice GROUP BY BillingCountry ORDER BY TotalSales DESC'}`


[('USA', 523.0600000000003), ('Canada', 303.9599999999999), ('France', 195.09999999999994), ('Brazil', 190.09999999999997), ('Germany', 156.48), ('United Kingdom', 112.85999999999999), ('Czech Republic', 90.24000000000001), ('Portugal', 77.23999999999998), ('India', 75.25999999999999), ('Chile', 46.62), ('Ireland', 45.62), ('Hungary', 45.62), ('Austria', 42.62), ('Finland', 41.620000000000005), ('Netherlands', 40.62), ('Norway', 39.62), ('Sweden', 38.620000000000005), ('Poland', 37.620000000000005), ('Italy', 37.620000000000005), ('Denmark', 37.620000000000005), ('Australia', 37.620000000000005), ('Argentina', 37.620000000000005), ('Spain', 37.62), ('Belgium', 37.62)]The total sales per country are as follows:

1. USA: $523.06
2. Canada: $303.96
3. France: $195.10
4. Brazil: $190.10
5. Germany: $156.48
6. United Kingdom: $112.86
7. Czech Republic: $90.24
8. Portugal: $77.24
9. India: $75.26
10. Chile: $46.62

The country whose customers spent the most is the USA with a total sales amount of $523.06.The total sales per country are as follows:

1. USA: $523.06
2. Canada: $303.96
3. France: $195.10
4. Brazil: $190.10
5. Germany: $156.48
6. United Kingdom: $112.86
7. Czech Republic: $90.24
8. Portugal: $77.24
9. India: $75.26
10. Chile: $46.62

The country whose customers spent the most is the USA with a total sales amount of $523.06.

> Finished chain.

{'input': "List the total sales per all countries. Which country's customers spent the most?",
 'output': 'The total sales per country are as follows:\n\n1. USA: $523.06\n2. Canada: $303.96\n3. France: $195.10\n4. Brazil: $190.10\n5. Germany: $156.48\n6. United Kingdom: $112.86\n7. Czech Republic: $90.24\n8. Portugal: $77.24\n9. India: $75.26\n10. Chile: $46.62\n\nThe country whose customers spent the most is the USA with a total sales amount of $523.06.'}

In [27]:
agent_executor.invoke({"input": "Describe the playlisttrack table"})

> Entering new SQL Agent Executor chain...

Invoking: `sql_db_list_tables` with `{}`


Album, Artist, Customer, Employee, Genre, Invoice, InvoiceLine, MediaType, Playlist, PlaylistTrack, Track
Invoking: `sql_db_schema` with `{'table_names': 'PlaylistTrack'}`



CREATE TABLE "PlaylistTrack" (
	"PlaylistId" INTEGER NOT NULL,
	"TrackId" INTEGER NOT NULL,
	PRIMARY KEY ("PlaylistId", "TrackId"),
	FOREIGN KEY("TrackId") REFERENCES "Track" ("TrackId"),
	FOREIGN KEY("PlaylistId") REFERENCES "Playlist" ("PlaylistId")
)

/*
3 rows from PlaylistTrack table:
PlaylistId	TrackId
1	3402
1	3389
1	3390
*/The `PlaylistTrack` table has the following columns:
- PlaylistId: INTEGER (NOT NULL)
- TrackId: INTEGER (NOT NULL)

It is a junction table with a composite primary key consisting of PlaylistId and TrackId. The table also has foreign key constraints referencing the `Track` table and the `Playlist` table.

Here are 3 sample rows from the `PlaylistTrack` table:
1. PlaylistId: 1, TrackId: 3402
2. PlaylistId: 1, TrackId: 3389
3. PlaylistId: 1, TrackId: 3390The `PlaylistTrack` table has the following columns:
- PlaylistId: INTEGER (NOT NULL)
- TrackId: INTEGER (NOT NULL)

It is a junction table with a composite primary key consisting of PlaylistId and TrackId. The table also has foreign key constraints referencing the `Track` table and the `Playlist` table.

Here are 3 sample rows from the `PlaylistTrack` table:
1. PlaylistId: 1, TrackId: 3402
2. PlaylistId: 1, TrackId: 3389
3. PlaylistId: 1, TrackId: 3390

> Finished chain.

{'input': 'Describe the playlisttrack table',
 'output': 'The `PlaylistTrack` table has the following columns:\n- PlaylistId: INTEGER (NOT NULL)\n- TrackId: INTEGER (NOT NULL)\n\nIt is a junction table with a composite primary key consisting of PlaylistId and TrackId. The table also has foreign key constraints referencing the `Track` table and the `Playlist` table.\n\nHere are 3 sample rows from the `PlaylistTrack` table:\n1. PlaylistId: 1, TrackId: 3402\n2. PlaylistId: 1, TrackId: 3389\n3. PlaylistId: 1, TrackId: 3390'}